name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ui:
    path: packages/ui/

dev_dependencies:
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true