name: presentation
description: "Presentation Module"

version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:

  domain:
    path: ../domain
  data:
    path: ../data
  riverpod: ^2.5.1
  lints: ^4.0.0

dev_dependencies:
